language: android
dist: trusty
android:
    components:
        - tools
        - platform-tools
        - tools
                
before_install:
  - touch $HOME/.android/repositories.cfg
  - yes | sdkmanager "platforms;android-28"
  - yes | sdkmanager "build-tools;28.0"
  
script:
    - ./gradlew build connectedCheck --stacktrace